import { futureDateTime, futureDateStr, uid } from "./utils.js";

const ADULT_NAV = [
  { id: "dashboard", label: "Dashboard", icon: "🏠" },
  { id: "missions", label: "Missions", icon: "🚀" },
  { id: "calendar", label: "Calendar", icon: "📅" },
  { id: "goals", label: "Goals", icon: "🎯" },
  { id: "habits", label: "Habits", icon: "✨" },
  { id: "finances", label: "Finances", icon: "💰" },
  { id: "journal", label: "Journal", icon: "📓" },
  { id: "resources", label: "Resources", icon: "🔖" },
  { id: "achievements", label: "Achievements", icon: "🏆" },
  { id: "stats", label: "Stats", icon: "📊" },
  { id: "settings", label: "Settings", icon: "⚙️" },
];

const STUDENT_NAV = [
  { id: "dashboard", label: "Dashboard", icon: "🏠" },
  { id: "school", label: "School", icon: "🎓" },
  { id: "goals", label: "Goals", icon: "🎯" },
  { id: "calendar", label: "Calendar", icon: "📅" },
  { id: "habits", label: "Habits", icon: "✨" },
  { id: "friends", label: "Friends", icon: "👥" },
  { id: "journal", label: "Journal", icon: "📓" },
  { id: "achievements", label: "Achievements", icon: "🏆" },
  { id: "resources", label: "Resources", icon: "🔖" },
  { id: "messages", label: "Messages", icon: "💬" },
  { id: "settings", label: "Settings", icon: "⚙️" },
];

function widget(w) {
  return { id: uid(), hidden: false, layout: { x: 0, y: 0, w: 0, h: 0 }, ...w };
}

export function adultDefaults() {
  return {
    template: "adult",
    theme: {
      accent: "#22d3ee",
      accent2: "#3b82f6",
      accent3: "#a855f7",
      bgFrom: "#04030d",
      bgTo: "#050818",
    },
    text: {
      title: "Michael's Life Dashboard",
      subtitle: "Purpose in motion. 🚀",
      welcomeMessage: "Welcome back, Michael",
      sidebarBrand: "T-Minus",
      sidebarSubtitle: "Dashboard",
      brandEmoji: "🚀",
      missionBoxTitle: "You are in Mission Mode",
      missionBoxText: "Focus. Execute. Repeat.",
      progressLabel: "Overall Progress",
      progressText: "You're building your future.",
      quote: "I can do all things through Christ who strengthens me.",
      quoteAuthor: "Philippians 4:13",
      focusToday: "Focus. Faith. Family. Future.",
    },
    profile: {
      name: "Michael Lee",
      title: "Mission Builder",
      emoji: "🧑🏾",
      image: null,
      level: 12,
      xp: 2450,
      xpMax: 5000,
    },
    navItems: ADULT_NAV,
    widgets: [
      widget({
        type: "countdown",
        title: "Preaching at Joshua Tabernacle",
        subtitle: "Sunday Service",
        icon: "⛪",
        size: "sm",
        order: 0,
        accent: "var(--accent-3)",
        targetDate: futureDateTime(2, 10, 0),
        ctaLabel: "Message Prep In Progress",
        category: "faith",
        layout: { x: 0, y: 0, w: 3, h: 6 },
      }),
      widget({
        type: "countdown",
        title: "Preaching at Taylortown Church",
        subtitle: "Sermon Series: Faith In Action",
        icon: "⛪",
        size: "sm",
        order: 1,
        accent: "var(--accent)",
        targetDate: futureDateTime(9, 11, 30),
        ctaLabel: "Sermon Series: Faith In Action",
        category: "faith",
        layout: { x: 0, y: 6, w: 3, h: 6 },
      }),
      widget({
        type: "clock",
        title: "Command Clock",
        icon: "🕐",
        size: "tall",
        order: 2,
        text: "Stay Focused",
        extraValue: "Your future is in your hands.",
        layout: { x: 3, y: 0, w: 4, h: 12 },
      }),
      widget({
        type: "calendar",
        title: "Calendar",
        icon: "📅",
        size: "tall",
        order: 3,
        layout: { x: 7, y: 0, w: 5, h: 7 },
      }),
      widget({
        type: "countdown",
        title: "Birthday",
        subtitle: "Leveling Up!",
        icon: "🎂",
        size: "sm",
        order: 4,
        accent: "#f59e0b",
        targetDate: futureDateTime(137, 0, 0),
        category: "personal",
        layout: { x: 0, y: 12, w: 3, h: 6 },
      }),
      widget({
        type: "countdown",
        title: "Graduation",
        subtitle: "Master of Divinity",
        icon: "🎓",
        size: "md",
        order: 5,
        accent: "var(--accent)",
        targetDate: futureDateTime(23, 10, 0),
        current: 76,
        target: 100,
        extraLabel: "On Track",
        category: "school",
        ctaLabel: "MISSION CRITICAL",
        layout: { x: 7, y: 7, w: 5, h: 5 },
      }),
      widget({
        type: "countdown",
        title: "Christmas",
        subtitle: "The Season of Joy",
        icon: "🎄",
        size: "sm",
        order: 6,
        accent: "#22c55e",
        targetDate: futureDateTime(210, 0, 0),
        category: "personal",
        layout: { x: 0, y: 18, w: 3, h: 6 },
      }),
      widget({
        type: "ninetyday",
        title: "90-Day Run",
        subtitle: "Personal Best",
        icon: "🏃",
        size: "md",
        order: 7,
        accent: "#22c55e",
        startDate: futureDateStr(-24),
        totalDays: 90,
        category: "health",
        layout: { x: 3, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "reading",
        title: "Reading Goal",
        subtitle: "24 Books in 2026",
        icon: "📖",
        size: "md",
        order: 8,
        accent: "var(--accent-3)",
        current: 14,
        target: 24,
        unit: "Books Read",
        extraLabel: "Current Book",
        extraValue: "Atomic Habits",
        extraSub: "by James Clear",
        category: "personal",
        layout: { x: 5, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "savings",
        title: "Savings Goal",
        subtitle: "Financial Freedom Fund",
        icon: "💵",
        size: "md",
        order: 9,
        accent: "var(--accent)",
        current: 7250,
        target: 10000,
        unit: "$",
        category: "finance",
        layout: { x: 7, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "checklist",
        title: "Today's Missions",
        icon: "🎯",
        size: "md",
        order: 10,
        accent: "var(--accent)",
        items: [
          { id: uid(), label: "Spend time with God", done: true },
          { id: uid(), label: "Workout", done: true },
          { id: uid(), label: "Study for Midterm", done: false },
          { id: uid(), label: "Finish Sermon Outline", done: false },
          { id: uid(), label: "Read 30 Pages", done: true },
        ],
        layout: { x: 9, y: 12, w: 3, h: 8 },
      }),
    ],
    events: [
      {
        id: uid(),
        date: futureDateStr(2),
        title: "Preaching at Joshua Tabernacle",
        time: "10:00 AM",
        category: "faith",
        color: "var(--accent-3)",
      },
      {
        id: uid(),
        date: futureDateStr(9),
        title: "Preaching at Taylortown Church",
        time: "11:30 AM",
        category: "faith",
        color: "var(--accent)",
      },
      {
        id: uid(),
        date: futureDateStr(6),
        title: "90-Day Run Checkpoint",
        time: "",
        category: "health",
        color: "#22c55e",
      },
      {
        id: uid(),
        date: futureDateStr(46),
        title: "Midterm Exams",
        time: "",
        category: "school",
        color: "var(--accent)",
      },
      {
        id: uid(),
        date: futureDateStr(23),
        title: "Graduation Ceremony",
        time: "10:00 AM",
        category: "school",
        color: "var(--accent)",
      },
      {
        id: uid(),
        date: futureDateStr(133),
        title: "Conference Trip",
        time: "",
        category: "business",
        color: "#ec4899",
      },
    ],
    habits: [
      { id: uid(), label: "Morning Prayer", icon: "🙏", streak: 12, completedToday: true },
      { id: uid(), label: "Workout", icon: "💪", streak: 9, completedToday: true },
      { id: uid(), label: "Read Scripture", icon: "📖", streak: 12, completedToday: false },
      { id: uid(), label: "No Sugar", icon: "🚫", streak: 5, completedToday: true },
      { id: uid(), label: "Journal", icon: "📓", streak: 7, completedToday: false },
      { id: uid(), label: "Sermon Prep", icon: "📝", streak: 3, completedToday: true },
      { id: uid(), label: "Early Sleep", icon: "🌙", streak: 4, completedToday: true },
      { id: uid(), label: "Cold Shower", icon: "🚿", streak: 12, completedToday: true },
    ],
    journal: [
      {
        id: uid(),
        date: futureDateStr(-1),
        title: "Staying the course",
        body: "Grateful for another day of progress. The 90-day run is teaching me more about discipline than I expected.",
        mood: "💪",
      },
      {
        id: uid(),
        date: futureDateStr(-3),
        title: "Sermon prep breakthrough",
        body: "Finally found the right thread for Sunday. Faith in Action is coming together.",
        mood: "🙏",
      },
    ],
    achievements: [
      {
        id: uid(),
        title: "7-Day Streak",
        description: "Completed habits 7 days in a row.",
        icon: "🔥",
        unlocked: true,
        date: futureDateStr(-5),
      },
      {
        id: uid(),
        title: "First Sermon Delivered",
        description: "Preached your first sermon on T-Minus.",
        icon: "⛪",
        unlocked: true,
        date: futureDateStr(-40),
      },
      {
        id: uid(),
        title: "Halfway to Graduation",
        description: "Crossed 50% progress toward your degree.",
        icon: "🎓",
        unlocked: true,
        date: futureDateStr(-60),
      },
      {
        id: uid(),
        title: "$5,000 Saved",
        description: "Reached the halfway mark on your savings goal.",
        icon: "💰",
        unlocked: true,
        date: futureDateStr(-20),
      },
      {
        id: uid(),
        title: "90-Day Finisher",
        description: "Complete the full 90-day personal challenge.",
        icon: "🏁",
        unlocked: false,
      },
      {
        id: uid(),
        title: "24 Books a Year",
        description: "Finish your full reading goal.",
        icon: "📚",
        unlocked: false,
      },
    ],
    resources: [
      { id: uid(), title: "Sermon Outline Template", subtitle: "Faith In Action series notes", icon: "📄" },
      { id: uid(), title: "Seminary Reading List", subtitle: "Required texts for this semester", icon: "📚" },
      { id: uid(), title: "90-Day Training Plan", subtitle: "Week-by-week structure", icon: "🏃" },
      { id: uid(), title: "Budget Tracker Sheet", subtitle: "Savings & finances", icon: "💵" },
    ],
    friends: [],
    messages: [],
    vitals: {
      streakDays: 12,
      focusLevel: 82,
      energyPercent: 87,
      systemStatus: "All Systems Go",
      affirmation: "You've got purpose. Let's move.",
    },
  };
}

export function studentDefaults() {
  return {
    template: "student",
    theme: {
      accent: "#22d3ee",
      accent2: "#ec4899",
      accent3: "#a855f7",
      bgFrom: "#0a0518",
      bgTo: "#150827",
    },
    text: {
      title: "Maya's Life Dashboard",
      subtitle: "Dream Big. Study Hard. Shine Bright. ✨",
      welcomeMessage: "Welcome back, Maya",
      sidebarBrand: "Starpath",
      sidebarSubtitle: "Command Center",
      brandEmoji: "🌙",
      missionBoxTitle: "Mission Mode",
      missionBoxText: "Focus. Plan. Achieve. Level up every day.",
      progressLabel: "Next Study Star",
      progressText: "You've got this, Maya!",
      quote: "You are braver than you believe, stronger than you seem, and smarter than you think.",
      quoteAuthor: "A. A. Milne",
      focusToday: "Focus Today: Consistency",
    },
    profile: {
      name: "Maya",
      title: "Future Architect",
      emoji: "👧🏽",
      image: null,
      level: 16,
      xp: 3450,
      xpMax: 5000,
    },
    navItems: STUDENT_NAV,
    widgets: [
      widget({
        type: "countdown",
        title: "Math Exam",
        subtitle: "Algebra II",
        icon: "🧮",
        size: "sm",
        order: 0,
        accent: "var(--accent-2)",
        targetDate: futureDateTime(2, 8, 0),
        ctaLabel: "View Study Plan",
        category: "school",
        layout: { x: 0, y: 0, w: 3, h: 6 },
      }),
      widget({
        type: "clock",
        title: "Command Clock",
        icon: "🕐",
        size: "tall",
        order: 1,
        text: "Stay Focused",
        extraValue: "Your future is in your hands.",
        layout: { x: 3, y: 0, w: 4, h: 12 },
      }),
      widget({
        type: "calendar",
        title: "Calendar",
        icon: "📅",
        size: "tall",
        order: 2,
        layout: { x: 7, y: 0, w: 5, h: 7 },
      }),
      widget({
        type: "countdown",
        title: "Youth Choir",
        subtitle: "Spring Performance",
        icon: "🎵",
        size: "sm",
        order: 3,
        accent: "var(--accent-3)",
        targetDate: futureDateTime(9, 19, 0),
        ctaLabel: "Practice Schedule",
        category: "personal",
        layout: { x: 0, y: 6, w: 3, h: 6 },
      }),
      widget({
        type: "countdown",
        title: "Graduation Countdown",
        subtitle: "Class of 2027",
        icon: "🎓",
        size: "md",
        order: 4,
        accent: "var(--accent-3)",
        targetDate: futureDateTime(376, 0, 0),
        category: "school",
        ctaLabel: "Keep Going!",
        layout: { x: 7, y: 7, w: 5, h: 5 },
      }),
      widget({
        type: "countdown",
        title: "Birthday",
        subtitle: "Sweet 16!",
        icon: "🎂",
        size: "sm",
        order: 5,
        accent: "#f59e0b",
        targetDate: futureDateTime(139, 0, 0),
        category: "personal",
        layout: { x: 0, y: 12, w: 3, h: 6 },
      }),
      widget({
        type: "countdown",
        title: "Christmas",
        subtitle: "The Season of Joy",
        icon: "🎄",
        size: "sm",
        order: 6,
        accent: "#22c55e",
        targetDate: futureDateTime(210, 0, 0),
        category: "personal",
        layout: { x: 0, y: 20, w: 3, h: 6 },
      }),
      widget({
        type: "checklist",
        title: "Homework Progress",
        icon: "📋",
        size: "md",
        order: 7,
        accent: "var(--accent)",
        items: [
          { id: uid(), label: "Math Problem Set", done: true },
          { id: uid(), label: "English Essay", done: false },
          { id: uid(), label: "Biology Lab Report", done: false },
          { id: uid(), label: "History Reading", done: true },
          { id: uid(), label: "Spanish Vocab", done: false },
        ],
        category: "school",
        layout: { x: 3, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "reading",
        title: "Reading Goal",
        subtitle: "Read more. Grow more.",
        icon: "📖",
        size: "md",
        order: 8,
        accent: "var(--accent-3)",
        current: 18,
        target: 24,
        unit: "Books Completed",
        extraLabel: "Current Book",
        extraValue: "The Inheritance Games",
        extraSub: "by Jennifer Lynn Barnes",
        category: "personal",
        layout: { x: 5, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "study",
        title: "Study Hours",
        subtitle: "GPA Goal: 4.0",
        icon: "📚",
        size: "md",
        order: 9,
        accent: "var(--accent)",
        current: 32,
        target: 40,
        unit: "Study Hours This Month",
        extraLabel: "Current GPA",
        extraValue: "3.6",
        category: "school",
        layout: { x: 7, y: 12, w: 2, h: 8 },
      }),
      widget({
        type: "checklist",
        title: "Today's Missions",
        icon: "⭐",
        size: "md",
        order: 10,
        accent: "var(--accent-2)",
        items: [
          { id: uid(), label: "Math homework", done: true },
          { id: uid(), label: "Study for Biology quiz", done: true },
          { id: uid(), label: "Basketball practice", done: false },
          { id: uid(), label: "Call Grandma", done: false },
          { id: uid(), label: "Finish art project", done: true },
        ],
        layout: { x: 9, y: 12, w: 3, h: 8 },
      }),
    ],
    events: [
      {
        id: uid(),
        date: futureDateStr(2),
        title: "Math Exam - Algebra II",
        time: "8:00 AM",
        category: "school",
        color: "var(--accent-2)",
      },
      {
        id: uid(),
        date: futureDateStr(9),
        title: "Youth Choir Spring Performance",
        time: "7:00 PM",
        category: "personal",
        color: "var(--accent-3)",
      },
      {
        id: uid(),
        date: futureDateStr(5),
        title: "Biology Quiz",
        time: "",
        category: "school",
        color: "var(--accent)",
      },
      {
        id: uid(),
        date: futureDateStr(14),
        title: "Basketball Practice",
        time: "4:00 PM",
        category: "personal",
        color: "#f59e0b",
      },
      {
        id: uid(),
        date: futureDateStr(139),
        title: "Sweet 16 Birthday",
        time: "",
        category: "personal",
        color: "#f59e0b",
      },
    ],
    habits: [
      { id: uid(), label: "Read 20 Minutes", icon: "📖", streak: 12, completedToday: true },
      { id: uid(), label: "Homework Before Screen Time", icon: "📝", streak: 12, completedToday: true },
      { id: uid(), label: "Practice Piano", icon: "🎹", streak: 6, completedToday: false },
      { id: uid(), label: "Drink Water", icon: "💧", streak: 12, completedToday: true },
      { id: uid(), label: "Gratitude Journal", icon: "🙏", streak: 8, completedToday: true },
      { id: uid(), label: "Stretch / Move", icon: "🤸", streak: 4, completedToday: false },
      { id: uid(), label: "Tidy Room", icon: "🧹", streak: 3, completedToday: true },
      { id: uid(), label: "Kind Word to Someone", icon: "💛", streak: 12, completedToday: true },
    ],
    journal: [
      {
        id: uid(),
        date: futureDateStr(-1),
        title: "Choir practice went great!",
        body: "We nailed the harmony today. Ms. Reyes said we are ready for the spring performance.",
        mood: "🎵",
      },
      {
        id: uid(),
        date: futureDateStr(-4),
        title: "Nervous about the math exam",
        body: "Going to study a little more each night this week so I feel ready.",
        mood: "😬",
      },
    ],
    achievements: [
      {
        id: uid(),
        title: "7-Day Streak",
        description: "Completed habits 7 days in a row.",
        icon: "🔥",
        unlocked: true,
        date: futureDateStr(-5),
      },
      {
        id: uid(),
        title: "Bookworm",
        description: "Read 15 books this year.",
        icon: "📚",
        unlocked: true,
        date: futureDateStr(-10),
      },
      {
        id: uid(),
        title: "Honor Roll",
        description: "Kept your GPA above 3.5 all semester.",
        icon: "🏅",
        unlocked: true,
        date: futureDateStr(-30),
      },
      {
        id: uid(),
        title: "Choir Star",
        description: "Performed a solo in the spring concert.",
        icon: "🎤",
        unlocked: false,
      },
      {
        id: uid(),
        title: "24 Books a Year",
        description: "Finish your full reading goal.",
        icon: "📖",
        unlocked: false,
      },
      {
        id: uid(),
        title: "Level 20",
        description: "Reach level 20 on your dashboard.",
        icon: "⭐",
        unlocked: false,
      },
    ],
    resources: [
      { id: uid(), title: "Algebra II Study Guide", subtitle: "Chapters 4-6 review", icon: "🧮" },
      { id: uid(), title: "Choir Sheet Music", subtitle: "Spring performance set", icon: "🎵" },
      { id: uid(), title: "Reading List 2026", subtitle: "24 books to finish", icon: "📚" },
    ],
    friends: [
      { id: uid(), title: "Zoe Martinez", subtitle: "Choir • Study buddy", icon: "👩🏻" },
      { id: uid(), title: "Priya Patel", subtitle: "Basketball • Lunch crew", icon: "👩🏽" },
      { id: uid(), title: "Jaden Cole", subtitle: "Math study group", icon: "🧑🏾" },
      { id: uid(), title: "Ella Kim", subtitle: "Best friend since 3rd grade", icon: "👧🏻" },
    ],
    messages: [
      {
        id: uid(),
        from: "Ms. Reyes (Choir)",
        preview: "Great rehearsal today! See you Thursday for the last run-through.",
        time: "2h ago",
        unread: true,
        avatar: "🎵",
      },
      {
        id: uid(),
        from: "Zoe Martinez",
        preview: "Want to study for the math exam together tomorrow?",
        time: "5h ago",
        unread: true,
        avatar: "👩🏻",
      },
      {
        id: uid(),
        from: "Mom",
        preview: "Don't forget we have dinner with Grandma on Sunday!",
        time: "1d ago",
        unread: false,
        avatar: "💛",
      },
    ],
    vitals: {
      streakDays: 12,
      focusLevel: 78,
      energyPercent: 92,
      systemStatus: "All Systems Go",
      affirmation: "Keep shining, Maya!",
    },
  };
}

export function defaultsFor(template) {
  return template === "adult" ? adultDefaults() : studentDefaults();
}

export const BUILTIN_THEMES = [
  {
    id: "builtin-adult",
    name: "Mission Control",
    emoji: "🚀",
    builtin: true,
    colors: adultDefaults().theme,
  },
  {
    id: "builtin-student",
    name: "Starpath",
    emoji: "🌙",
    builtin: true,
    colors: studentDefaults().theme,
  },
];

export const WIDGET_TYPES = [
  { type: "countdown", label: "Countdown", icon: "⏱️", description: "Count down to any date & time", size: "sm" },
  { type: "clock", label: "Clock", icon: "🕐", description: "Live analog + digital clock", size: "tall" },
  { type: "calendar", label: "Calendar", icon: "📅", description: "Month view of your events", size: "md" },
  { type: "progress", label: "Goal Progress", icon: "🎯", description: "Track progress toward any goal", size: "md" },
  { type: "ninetyday", label: "90-Day Challenge", icon: "🏃", description: "Day-by-day challenge tracker", size: "md" },
  { type: "checklist", label: "Checklist", icon: "✅", description: "Daily missions or to-dos", size: "md" },
  { type: "quote", label: "Quote / Scripture", icon: "💬", description: "Encouragement card", size: "sm" },
  { type: "savings", label: "Savings Goal", icon: "💵", description: "Track a financial goal", size: "md" },
  { type: "reading", label: "Reading Goal", icon: "📖", description: "Books completed this year", size: "md" },
  { type: "study", label: "Study Goal", icon: "📚", description: "Study hours or GPA tracker", size: "md" },
  { type: "text", label: "Custom Text", icon: "📝", description: "Freeform note card", size: "sm" },
  { type: "image", label: "Image Card", icon: "🖼️", description: "Upload a photo or logo", size: "md" },
];
